### PR TITLE
Support rounding multiple nets at once

### PR DESCRIPTION
**Pull request by stiff**
Hi. Thanks for sharing nice plugin. I tried it and immediately got an idea how to improve it: https://youtu.be/w8m3tMin9Q0

### CODE REVIEW

**Comment by easyw** [comment]
HI @stiff 
this is a nice addition, but for flex pcb, when rounding traces we should use conical radius bends.
This can be easily accomplished manually, but with a multi-selection, we would need to add a field for the conical adjustment...
You can see at my video that I used a manual conical adjustment on each track 
https://youtu.be/NIyFj2FNNf8?t=55

**Comment by stiff** [comment]
Yes, sure. But still, we should start somewhere and then perfect it.
Finding those radiuses automatically is not so trivial.

**Comment by easyw** [comment]
> But still, we should start somewhere and then perfect it.

creating the multiple curved traces without the cone adjustment is not a way to go for a good layout ...
before merging the multiple traces option we should need to improve it to a (pseudo) conical feature...

**Comment by stiff** [comment]
User can select arbitrary tracks, not necessarily going parallel. That's why even determining direction of the vector along which you should alter the rounding radius is not always makes any sense.

You can highlight the net that is about to be modified and add button "Round single net" that will not close the dialog but proceed to next net after rounding. That will noticeable reduce number of clicks required by user to get the desired result. Again, tricky part here is to find the outmost track to start with.

**Comment by stiff** [comment]
Btw, when just two tracks are selected it still works exactly as it was before. No change in behaviour compared to your video are required. Don't really understand what are you arguing with.

**Comment by easyw** [comment]
> You can highlight the net that is about to be modified and add button "Round single net" that will not close the dialog but proceed to next net after rounding.

This is unfortunately not possible.
I already tested this option and it is not working correctly with the kicad undo function... Unfortunately Action Plugins have some strong restriction...


> Btw, when just two tracks are selected it still works exactly as it was before. No change in behaviour compared to your video are required.

Correct, but the plugin is intended to offer a correct way to create a RF curved trace and this implies you have to choose the radius depending on a different choice each track.

I'm sorry but I think we need to wait until V6 will implement curved traces to have more options.

**Pull request closed without merging**
